### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by UphkcRNqmafQWcSSSSSS** [uni-helper/vite-plugin-uni-platform#2]
### 除页面外，必须有回退文件
/pages/user.h5.vue

控制台输出：
pages/user not found

router mode: history下
<img width="1249" alt="image" src="https://github.com/uni-helper/vite-plugin-uni-platform/assets/4394948/5ba180ff-c179-433b-b902-6ac07cea37b9">

### 复现

[demo](https://github.com/UphkcRNqmafQWcSSSSSS/vite-plugin-uni-platform-demo)

### 系统信息

```Shell
System:
    OS: macOS 13.4.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 7.12 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.13.0 - ~/.nvm/versions/node/v18.13.0/bin/node
    npm: 8.19.3 - ~/.nvm/versions/node/v18.13.0/bin/npm
  Browsers:
    Edge: 115.0.1901.188
    Safari: 16.5.2
```

### 使用的包管理器

pnpm

### 核对

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 检查是否已经有一个报告相同错误的问题，以避免重复创建。
- [X] 这是一个具体的错误。请开启 GitHub 讨论你的疑问。
- [X] 所提供的复现是这个问题的 [最小复现](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by KeJunMao** [comment]
非常感谢你的反馈，不过这是一个实验性（WIP）插件，请勿用于生产

**Comment by KeJunMao** [comment]
try v0.0.2
